/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PerksImport } from './routes/perks'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PerksRoute = PerksImport.update({
  id: '/perks',
  path: '/perks',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/perks': {
      id: '/perks'
      path: '/perks'
      fullPath: '/perks'
      preLoaderRoute: typeof PerksImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/perks': typeof PerksRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/perks': typeof PerksRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/perks': typeof PerksRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/perks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/perks'
  id: '__root__' | '/' | '/perks'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PerksRoute: typeof PerksRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PerksRoute: PerksRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/perks"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/perks": {
      "filePath": "perks.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
