debug: true
server:
  port: 3000
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://deep-grouse-63.clerk.accounts.dev
          audiences: TowerWiki
  sql:
    init:
      platform: postgresql
      mode: always

    output:
      ansi:
        enabled: always

  datasource:
    url: jdbc:postgresql://localhost:5432/wikiDB
    username: salt
    password: secret


  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR